global:
    checkNewVersion: false
    sendAnonymousUsage: false

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"
    ping:
        address: ":8082"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: true
    file:
        filename: /etc/traefik/dynamic.yml
        watch: true

ping:
    entryPoint: "ping"

api:
    dashboard: true

log:
    level: ERROR
